name: Test PR

on: pull_request

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          cache: maven
      
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          path: "https://github.com/irori-ab/platform-school-petclinic-luciandragos"
          base: ""
          head: ${{ github.ref_name }}
